// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBEsB3zhLBCJg69xspSzUXzPSEdUtANh8',
    appId: '1:924677761113:web:43c4bb0611b2950f9be948',
    messagingSenderId: '924677761113',
    projectId: 'gbkhackathon',
    authDomain: 'gbkhackathon.firebaseapp.com',
    storageBucket: 'gbkhackathon.appspot.com',
    measurementId: 'G-YPEBCVMD0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwK8yxaCw56Jr-wwb75U9BHyQY1UC5Nuk',
    appId: '1:924677761113:android:91183dec0adff7c29be948',
    messagingSenderId: '924677761113',
    projectId: 'gbkhackathon',
    storageBucket: 'gbkhackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-EyDYlVF9kXMvNP6CI1D99xQWZFh-iPg',
    appId: '1:924677761113:ios:5ddaf70aeef5a7229be948',
    messagingSenderId: '924677761113',
    projectId: 'gbkhackathon',
    storageBucket: 'gbkhackathon.appspot.com',
    iosClientId: '924677761113-lt1se3gtphujethasqvvn9br62rb3k58.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbkHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-EyDYlVF9kXMvNP6CI1D99xQWZFh-iPg',
    appId: '1:924677761113:ios:5ddaf70aeef5a7229be948',
    messagingSenderId: '924677761113',
    projectId: 'gbkhackathon',
    storageBucket: 'gbkhackathon.appspot.com',
    iosClientId: '924677761113-lt1se3gtphujethasqvvn9br62rb3k58.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbkHackathon',
  );
}
